### ISSUE TITLE
Villagers don't optimize from trading with the workstation optimization option

### ISSUE THREAD

**Issue by Folas1337** [xGinko/VillagerOptimizer#12]
It seems that if I enable the workstation optimization, the villagers don't get optimized when traded with but the comments of the config.yml state it should optimize them.

Here's the configuration I used:
```yaml
  workstation-optimization:
    # When enabled, villagers that have a job and have been traded with at least once will become optimized,
    # if near their workstation. If the workstation is broken, the villager will become unoptimized again.
    enable: true
    # After a workstation has been placed, the plugin will wait for the configured amount of time in ticks
    # for a villager to claim that workstation. Not recommended to go below 100 ticks.
    check-linger-duration-ticks: 100
    # The radius in blocks a villager can be away from the player when he places a workstation.
    # The closest unoptimized villager to the player will be optimized.
    search-radius-in-blocks: 2.0
    # Cooldown in seconds until a villager can be optimized again using a workstation.
    # Here for configuration freedom. Recommended to leave as is to not enable any exploitable behavior.
    optimize-cooldown-seconds: 6
    # Only optimize/unoptimize by workstation when player is sneaking during place or break. Useful for villager rolling.
    only-when-sneaking: true
    # Sends players a message when they successfully optimized a villager.
    notify-player: true
    log: false
```

And since this is the only option I want to use on my server, this doesn't work.
